name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ] # Замените на [ master ], если у вас главная ветка называется так

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Можно указать вашу версию Node, например 18 или 20
          cache: 'npm'

      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./built # Используйте './build' ЕСЛИ у вас Create React App, или './dist' ЕСЛИ у вас Vite

  deploy:
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # (или просто пустая строка, рантайн подставит нужный раннер) -> 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions-deploy-pages@v4